title: Nihan Akıncı
logo: /assets/img/Nihan_Akinci.jpeg
description: I am a Junior DevOps Engineer, passionate about expanding my knowledge in technology; particularly in Kubernetes and Containers. Previously a Business Analyst, I bring an understanding of how to align technology with business, a skill that is valuable in the DevOps environment.
show_downloads: true
theme: jekyll-theme-minimal
