title: Nihan Akıncı
logo: /assets/img/Nihan_Akinci.jpeg
description: I'm a Junior DevOps Engineer with a passion for technology, focusing on Kubernetes and Containers. As a former Business Analyst, I bring a valuable skill set for aligning technology with business needs in the DevOps environment.
show_downloads: true
theme: jekyll-theme-minimal
